fx_version 'cerulean'
author 'Marttins#0011'
game 'gta5'
description 'A simple christmas script for QBCore'
client_script 'client.lua'
server_script 'server.lua'
shared_script 'config.lua'
files 'stream/vms_gift.ytyp'
data_file 'DLC_ITYP_REQUEST' 'vms_gift.ytyp'
lua54 'true'